# NUMPY ASSIGNMENTS

In [1]:
import numpy as np

# 1. PRODUCT OF 2-DIM AND 3-DIM ARRAYS

# using multiplication function for 2-dim and 3-dim arrays respectively

In [2]:
num = np.arange(15).reshape(3,5) # creating a 2 dimensional array in range of 15

num1 = np.array([9,10,12,13,22,14,0,2,7,3,5,11,1,4,8]).reshape(3,5)

In [3]:
num

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
num1

array([[ 9, 10, 12, 13, 22],
       [14,  0,  2,  7,  3],
       [ 5, 11,  1,  4,  8]])

In [5]:
number=np.multiply(num,num1) # using the multiplication function
number

array([[  0,  10,  24,  39,  88],
       [ 70,   0,  14,  56,  27],
       [ 50, 121,  12,  52, 112]])

In [6]:
# Creating a 3 dimensional array
num2 = np.arange(12).reshape(2,2,3)
num3 = np.arange(12,24).reshape(2,2,3)

In [7]:
num2
num2.shape

(2, 2, 3)

In [8]:
num3

array([[[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [9]:
number1 = np.multiply(num2,num3)
number1

array([[[  0,  13,  28],
        [ 45,  64,  85]],

       [[108, 133, 160],
        [189, 220, 253]]])

# USING DOT FUNCTION FOR 2-DIM AND 3-DIM ARRAYS

In [10]:
data1 = np.arange(12).reshape(3, 4) #creating a 2 dimensional array
data2 = np.arange(24).reshape(3,4,2) #creating a 3 dimensional array


In [11]:
data1 # 2 dimensional array in range 12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
data2 # 3 dimensional array in range 12

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [13]:
data = np.dot(data1,data2) #dot product of both dat1 and data2

In [14]:
data

array([[[ 28,  34],
        [ 76,  82],
        [124, 130]],

       [[ 76,  98],
        [252, 274],
        [428, 450]],

       [[124, 162],
        [428, 466],
        [732, 770]]])

# 2.SIMPLE CALCULATION USING SIN, COS,TAN AND LOG

# calculating for sine

In [15]:
value = [0, np.pi/2]

In [16]:
value

[0, 1.5707963267948966]

In [17]:
value = np.array(value)
values_in_degrees = np.degrees(value)
values_in_degrees

array([ 0., 90.])

In [18]:
#The sin of the angles
sine_of_angles = np.sin(values_in_degrees)
sine_of_angles


array([0.        , 0.89399666])

In [19]:
value1 = [np.pi/3, np.pi]
value1

[1.0471975511965976, 3.141592653589793]

In [20]:
value1_in_degree = np.degrees(value1)
value1_in_degree

array([ 60., 180.])

In [21]:
sine_of_value1 = np.sin(value1_in_degree)
sine_of_value1


array([-0.30481062, -0.80115264])

In [22]:
sine_of_angles * sine_of_value1

array([-0.        , -0.71622778])

# calculating for cosine

In [23]:
x = [0, np.pi/2, np.pi/3, np.pi]
x

[0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

In [24]:
x1 = np.degrees(x)
x1

array([  0.,  90.,  60., 180.])

In [25]:
cosine_of_x1 = np.cos(x1)
cosine_of_x1

array([ 1.        , -0.44807362, -0.95241298, -0.59846007])

# calculating for tangent

In [26]:
y = [0, np.pi/2, np.pi/3, np.pi]
y

[0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

In [27]:
y1 = np.degrees(y)
y1

array([  0.,  90.,  60., 180.])

In [28]:
tan_of_y1 = np.tan(y1)
tan_of_y1

array([ 0.        , -1.99520041,  0.32004039,  1.33869021])

# calculation for logarithms 

In [29]:
integers = np.arange(10,26,5)
integers

array([10, 15, 20, 25])

In [30]:
#Natural logarithm of the array
print('Natural logarithm of the array is: ',np.log(integers))

Natural logarithm of the array is:  [2.30258509 2.7080502  2.99573227 3.21887582]


In [31]:
#Common logarithm i.e logarithm to base 10
print('Logarithm of the array to base 10 is: ',np.log10(integers))

Logarithm of the array to base 10 is:  [1.         1.17609126 1.30103    1.39794001]


In [32]:
#Logarithm to base 2
print('logarithm of the array to base 2 is: ',np.log2(integers))

logarithm of the array to base 2 is:  [3.32192809 3.9068906  4.32192809 4.64385619]


# 3. MULTIPLICATION OF MATRICES USING MATMUL

In [33]:
k = np.arange(15).reshape(5,3)

h = np.arange(15,30).reshape(3,5)

In [34]:
k

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
h

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
# multiplication using matmul
print('The multiplication of both arrays using matmul is:\n',np.matmul(k,h))


The multiplication of both arrays using matmul is:
 [[ 70  73  76  79  82]
 [250 262 274 286 298]
 [430 451 472 493 514]
 [610 640 670 700 730]
 [790 829 868 907 946]]


# 4. NUMPY PROGRAM TO CREATE A 3X3 IDENTITY MATRIX

In [37]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 5. CREATING A 3X3 MATRIX WITH VALUES RANGING FROM 2 TO 10

In [38]:
z = np.arange(2,11).reshape(3,3)
z

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 6. NUMPY PROGRAM TO CREATE A NEW SHAPE OF AN ARRAY WITHOUT CHANGING ITS DATA

In [39]:
v = np.arange(8).reshape(2,4)
v

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
v.shape

(2, 4)

In [41]:
V = v.T
V

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [42]:
V.shape

(4, 2)